name: Sam Ludford
description: sound - image - code
meta_description: sound - image - code

aboutPage: true

markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate]
plugins_dir: [jekyll-paginate]
paginate: 20
domain_name: 'http://samludford.github.io'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://samludford.github.io'
author:         'Sam Ludford'
# authorTwitter:  'YourTwitterUsername'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
